name: your_comfort_food
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  loading_animation_widget: ^1.2.1
  flutter_widget_from_html: ^0.9.0
  floating_navigation_bar: ^0.0.5
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9
  flutter_gemini: ^2.0.3
  iconify_flutter: ^0.0.5
  flutter_svg: ^1.1.5
  lottie: ^3.1.0
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/

